build:
  nodes:
    # Edge Zemit Build
    zemit:
      root_path: './'
      services:
        mysql: latest
        redis: 6
      resources:
        cpus: 1
      environment:
        selenium: true
        google_chrome:
          use_latest: true
        timezone: 'America/New_York'
        hosts:
          core.zemit.local: 127.0.0.1
        apache2:
          modules: ['rewrite']
          sites:
            zemit:
              host: core.zemit.local # also make sure to add under "hosts" above
              web_root: public/
              rules:
                - 'RewriteEngine On'
                - 'RewriteCond %{REQUEST_FILENAME} !-d'
                - 'RewriteCond %{REQUEST_FILENAME} !-f'
                - 'RewriteRule ^(.*)$ index.php?_url=/$1 [QSA,L]'
        php:
          version: 8.2.15
          compile_options: '--with-config-file-path=/home/scrutinizer/.phpenv/versions/8.2.15/etc --with-config-file-scan-dir=/home/scrutinizer/.phpenv/versions/8.2.15/etc/conf.d --prefix=/home/scrutinizer/.phpenv/versions/8.2.15 --libexecdir=/home/scrutinizer/.phpenv/versions/8.2.15/libexec --enable-intl --with-openssl --with-gd --enable-gd --with-jpeg-dir=/usr --with-png-dir=/usr --with-freetype-dir=/usr --enable-exif --with-libzip --with-zlib --with-zlib-dir=/usr --with-sodium --with-pdo-sqlite --enable-soap --enable-xmlreader --with-xsl --enable-ftp --with-tidy --with-xmlrpc --enable-sysvsem --enable-sysvshm --enable-sysvmsg --enable-shmop --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd --enable-pcntl --with-readline --enable-mbstring --with-curl --with-pgsql --with-pdo-pgsql --with-gettext --enable-sockets --with-bz2 --enable-bcmath --enable-calendar --with-libdir=lib --enable-fpm --enable-zts --with-gmp --with-kerberos --with-imap --with-imap-ssl --with-apxs2=/usr/bin/apxs --with-ldap --with-pear=/home/scrutinizer/.phpenv/versions/8.2.15/pear'
#          compile_options: '--with-config-file-path=/home/scrutinizer/.phpenv/versions/7.4.14/etc --with-config-file-scan-dir=/home/scrutinizer/.phpenv/versions/7.4.14/etc/conf.d --prefix=/home/scrutinizer/.phpenv/versions/7.4.14 --libexecdir=/home/scrutinizer/.phpenv/versions/7.4.14/libexec --enable-intl --with-openssl --with-gd --enable-gd --with-jpeg-dir=/usr --with-png-dir=/usr --with-freetype-dir=/usr --enable-exif --with-libzip --with-zlib --with-zlib-dir=/usr --with-sodium --with-pdo-sqlite --enable-soap --enable-xmlreader --with-xsl --enable-ftp --with-tidy --with-xmlrpc --enable-sysvsem --enable-sysvshm --enable-sysvmsg --enable-shmop --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd --enable-pcntl --with-readline --enable-mbstring --with-curl --with-pgsql --with-pdo-pgsql --with-gettext --enable-sockets --with-bz2 --enable-bcmath --enable-calendar --with-libdir=lib --enable-fpm --enable-maintainer-zts --with-gmp --with-kerberos --with-imap --with-imap-ssl --with-apxs2=/usr/bin/apxs --with-ldap --with-pear=/home/scrutinizer/.phpenv/versions/7.4.14/pear'
          # @link https://pecl.php.net/
          pecl_extensions:
            - psr
            - redis
            - memcached
            - apcu
            - phalcon-5.6.1
          ini:
            memory_limit: -1
      dependencies:
        before:
          - composer self-update
        after:
          - composer require --dev phalcon/ide-stubs:5.6.1
          - composer require --dev phpunit/phpunit
          - composer require --dev squizlabs/php_codesniffer
          - mysql -h 127.0.0.1 -u root -e 'create database zemit_core'
          - chmod +x ./bin/*.sh
          - mkdir .phalcon
          - touch .env
          - cp .env.scrutinizer .env
          - ./bin/migration-list.sh
          - ./bin/migration-run.sh
          - echo "xdebug.mode=coverage" > /home/scrutinizer/.phpenv/versions/8.2.15/etc/conf.d/xdebug.ini
      tests:
        stop_on_failure: false
        override:
          - command: php-scrutinizer-run --enable-security-analysis
          - command: phpcs-run
          - command: ./vendor/bin/phpunit
            coverage:
              file: phpunit-clover.xml
              format: php-clover
      cache:
        disabled: false
        directories:
          - ~/.composer
          - ~/.npm
          - vendor/
          - node_modules/
checks:
  php: true
filter:
  excluded_paths:
    - 'tests/' # test suite
    - 'src/Migrations/' # autogenerated
    - 'src/Models/Base/' # autogenerated
    - 'src/Functions/Dump.php' # debug features
  dependency_paths:
    - 'vendor/'
    - 'node_modules/'
