<!DOCTYPE html>
<html class="<?= $pageClass ?>">
    <head>
        <meta charset="utf-8"/>
        <title>McGill | Zemit</title>
        <meta content="" name="description"/>
        <meta content="" name="author"/>
        
        <link rel="apple-touch-icon" sizes="57x57" href="/assets/favicons/apple-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="/assets/favicons/apple-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="/assets/favicons/apple-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="/assets/favicons/apple-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="/assets/favicons/apple-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="/assets/favicons/apple-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="/assets/favicons/apple-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="/assets/favicons/apple-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="/assets/favicons/apple-icon-180x180.png">
        <link rel="icon" type="image/png" sizes="192x192"  href="/assets/favicons/android-icon-192x192.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/assets/favicons/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="96x96" href="/assets/favicons/favicon-96x96.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/assets/favicons/favicon-16x16.png">
        <link rel="manifest" href="/manifest.json">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="/assets/favicons/ms-icon-144x144.png">
        <meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="shortcut icon" href="/assets/img/favicon.ico" />
		<!-- CSS START -->
		<link href="/assets/css/bootstrap.min.css" rel="stylesheet">
		<link href="/assets/css/style.css" rel="stylesheet">
		<link href="/assets/libraries/angular-1.6.1/angular-csp.css" rel="stylesheet">
		<link href="/assets/libraries/slick-1.8.0/slick/slick.css" rel="stylesheet">
		<link href="/assets/libraries/slick-1.8.0/slick/slick-theme.css" rel="stylesheet">
		<link href="/assets/libraries/angularjs-slider-master/dist/rzslider.min.css" rel="stylesheet">
		<link href="/assets/libraries/ng-sortable-master/dist/ng-sortable.min.css" rel="stylesheet">
		<link href="/assets/css/frontend.css" rel="stylesheet">
		<link href="/assets/css/article.read.css" rel="stylesheet">
		<!-- CSS END -->
		<!--[if lt IE 9]>
			<script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
    </head>
    <body ng-app="zemit" ng-class="{loading: loading > 0}">
        <?php $this->partial('layouts/header');?>
        <?php echo $this->getContent();?>
        <?php $this->partial('layouts/footer');?>
        
        <script>
            var app = {
                user: JSON.parse('<?= json_encode($user) ?>')
            }
        </script>
        
        <!-- Go to www.addthis.com/dashboard to customize your tools -->
		<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-58d7fa31d9980a84"></script>
    </body>
</html>