<?php $statusCode = intval($this->response->getStatusCode());?>
<?php $message = trim(str_replace($statusCode, null, $this->response->getStatusCode()));?>
<div class="container-fluid text-center">
    <h1 class="error-title"><?php echo $statusCode;?></h1>
    <h6 class="text-semibold content-group">Oops, an error has occurred. <?php echo $message;?>!</h6>

    <div class="row">
        <div class="col-lg-4 col-lg-offset-5 col-sm-6 col-sm-offset-3">
            <div class="row">
                <div class="col-sm-6">
                    <a href="<?php echo $this->url->get(array('for' => 'backend'));?>" class="btn btn-primary btn-block content-group"><i class="icon-circle-left2 position-left"></i> Go to dashboard</a>
                </div>
            </div>
        </div>
    </div>
</div>