<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![}]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![}]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
    <!--<![}]-->
    <head>
        <meta charset="utf-8"/>
        <title>McGill | Zemit</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport"/>
        <meta content="" name="description"/>
        <meta content="" name="author"/>
        <!--<link rel="icon" type="image/png" href="/favicon.png" />-->
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
        <link rel="icon" href="/favicon.ico" type="image/x-icon">

        <?php $this->assets->outputCss('css-header-core'); ?>

        <!--[if lt IE 9]><script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script><![}]-->

        <script type="text/javascript">
            var app = new Object();
            app.init = function () {};
            var zemit = new Object();
        </script>
    </head>
    
    <body ng-app="zemit">
        <?php $loginLayout = (in_array($this->dispatcher->getControllerName(), array('login', 'errors', 'survey'), true)) ? true : false;?>
        
        <?php $this->partial('layouts/modals/view-details'); ?>
        <?php $this->partial('layouts/modals/edit-data'); ?>
        <?php $this->partial('layouts/modals/form-message'); ?>
        <?php $this->partial('layouts/main-navbar'); ?>
        <?php $loginContainerClass = ($loginLayout) ? 'login-container' : null;?>
        <div class="page-container <?php echo $loginContainerClass;?>">
            <div class="page-content">
                <?php $this->partial('layouts/main-sidebar'); ?>
                <div class="content-wrapper">
                    <?php $this->partial('layouts/page-header'); ?>
                    <div class="content">
                        <?php echo $this->getContent(); ?>
                        <?php $this->partial('layouts/footer'); ?>
                    </div>
                </div>
            </div>
        </div>

        <?php $this->assets->outputJs('js-footer-core'); ?>
        <?php $this->assets->outputJs('js-footer-page'); ?>
        <?php $this->assets->outputJs('js-footer-ctrl'); ?>
        
        <script>
        	var request = {
        		userIp: '<?= $this->request->getClientAddress() ?>',
        		uri: '<?= $this->request->getURI() ?>',
        		referer: '<?= $this->request->getHTTPReferer() ?>'
        	};
        </script>

        <?php
        $errorReportingAction = $this->url->get(array(
            'for' => 'backend-controller-action',
            'controller' => 'error',
            'action' => 'reporting',
        ));
        ?>
        
        <?php // $this->partial('layouts/form/model'); ?>
        
        <script type="text/javascript">
            (function () {
                app.init();
            }());
        </script>
    </body>
</html>