<?php $statusCode = intval($this->response->getStatusCode());?>
<?php $message = trim(str_replace($statusCode, null, $this->response->getStatusCode()));?>

<!-- SITE CONTENT WRAPPER START -->
<div class="site-content-wrapper">
	<div class="container">
	    
		<!-- SITE CONTENT START  -->
		<div class="site-content">
					    
			<!-- SITE CONTENT LEFT START -->
			<div class="site-page-content">
			    
				<!-- SINGLE CONTENT START -->
				<div class="page-content">
				    
					<!-- PAGE START -->
					<article class="post format-standard">
					    
						<!-- PAGE ENTRY START -->
						<div class="post-entry clearfix">
							<div class="page404-content text-center">
								<h1><?php echo $statusCode;?> <?php echo $message;?></h1>
								<h2>Oops, an error has occurred.</h2>
								<p>Please try to search for an article below.</p>
								<form log-type="search" log-form method="get" action="/article/search" class="search-form-widget clearfix">
									<input type="text" value="" placeholder="SEARCH" name="search" class="searchform-text">
									<button id="searchsubmit"><i class="fa fa-search"></i></button>
								</form>
								<img src="/assets/img/search.jpg" alt="Search" />
							</div>
						</div>
						<!-- PAGE ENTRY END -->
					</article>
					<!-- PAGE END -->
				</div>
				<!-- SINGLE CONTENT END -->
			</div>
			<!-- SITE CONTENT LEFT END -->
		</div>
		<!-- SITE CONTENT END  -->
	</div>
</div>
<!-- SITE CONTENT WRAPPER END -->